# Generated by Django 5.0.6 on 2024-07-07 17:21

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                (
                    "category_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=product.models.image_upload_path,
                        validators=[product.models.image_validate],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(default="TABLE_NO", max_length=255)),
                (
                    "table_img",
                    models.ImageField(
                        upload_to=product.models.image_upload_path,
                        validators=[product.models.image_validate],
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.PositiveIntegerField()),
                (
                    "product_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=product.models.image_upload_path,
                        validators=[product.models.image_validate],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("total_price", models.PositiveIntegerField()),
                ("ordered_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        default="CHOOSE THE TABLE NO:",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.table",
                    ),
                ),
            ],
        ),
    ]
