# Generated by Django 5.0.6 on 2024-07-07 17:30

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=product.models.image_upload_path,
                validators=[product.models.image_validate],
            ),
        ),
    ]
