# Generated by Django 5.0.6 on 2024-07-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_bill_order_item_bill_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_name",
            field=models.CharField(default="TABLE_NO:", max_length=255),
        ),
    ]
